include required("conveyor.conf")

# Replace IP with machine IP for testing on private network
app {
  site {
    copy-to = "./local-site"
    base-url = "localhost:5500"
    consistency-checks = "warn"
  }
  ignore-connection-issues-for-hosts += "localhost:5500"
}